#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom abc abc
#' @importFrom bayestestR point_estimate
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_density
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom graphics axis
#' @importFrom graphics legend
#' @importFrom graphics lines
#' @importFrom graphics par
#' @importFrom graphics plot
#' @importFrom graphics points
#' @importFrom graphics text
#' @importFrom graphics title
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom grDevices rgb
#' @importFrom kernlab kernelMatrix
#' @importFrom kernlab laplacedot
#' @importFrom kernlab rbfdot
#' @importFrom magrittr %>%
#' @importFrom methods new
#' @importFrom parallel mclapply
#' @importFrom plotly add_surface
#' @importFrom plotly add_trace
#' @importFrom plotly plot_ly
#' @importFrom randomcoloR randomColor
#' @importFrom scales alpha
#' @importFrom stats aggregate
#' @importFrom stats complete.cases
#' @importFrom stats dist
#' @importFrom stats rbinom
#' @importFrom stats rexp
#' @importFrom stats rnorm
#' @importFrom stats runif
#' @importFrom utils globalVariables
#' @importFrom utils read.delim
#' @importFrom utils read.table
#' @importFrom utils setTxtProgressBar
#' @importFrom utils txtProgressBar
#' @importFrom utils write.table
## usethis namespace: end
NULL
